export const me = "me";

export const message = {
  bombs: [],
  players: [
    {
      alive: true,
      id: "1088ae85-2c17-4d24-9dd6-20879765bb48",
      name: "1088ae85-2c17-4d24-9dd6-20879765bb48",
      position: { x: 9, y: 9 },
      score: 0,
    },
    {
      alive: true,
      id: "2b22a6cd-7af3-4b38-84a0-224f231d29bb",
      name: "2b22a6cd-7af3-4b38-84a0-224f231d29bb",
      position: { x: 1, y: 1 },
      score: -1,
    },
    {
      alive: true,
      id: "5629497a-510a-4061-9ad2-3ea98c595172",
      name: "5629497a-510a-4061-9ad2-3ea98c595172",
      position: { x: 9, y: 9 },
      score: 0,
    },
    {
      alive: true,
      id: "72764de2-f0d9-4843-8ec4-ac9d2e4ad2dd",
      name: "72764de2-f0d9-4843-8ec4-ac9d2e4ad2dd",
      position: { x: 1, y: 1 },
      score: -1,
    },
    {
      alive: true,
      id: "789b0d44-3cc6-457c-a3e3-cf979253eded",
      name: "789b0d44-3cc6-457c-a3e3-cf979253eded",
      position: { x: 9, y: 1 },
      score: 0,
    },
    {
      alive: true,
      id: "baa47f6c-b00f-4c37-87dd-d0599a06805d",
      name: "baa47f6c-b00f-4c37-87dd-d0599a06805d",
      position: { x: 1, y: 9 },
      score: 0,
    },
    {
      alive: true,
      id: "dff44ed7-5354-4952-92ca-b301528623cc",
      name: "dff44ed7-5354-4952-92ca-b301528623cc",
      position: { x: 1, y: 9 },
      score: 0,
    },
    {
      alive: true,
      id: "e2d8d06a-4bee-4b3e-ae48-9acfe7c66c6d",
      name: "London Hack Night",
      position: { x: 1, y: 9 },
      score: 0,
    },
    {
      alive: true,
      id: "e7517640-7510-4cc7-9b62-d8f997b34949",
      name: "e7517640-7510-4cc7-9b62-d8f997b34949",
      position: { x: 1, y: 9 },
      score: 0,
    },
  ],
  serverEndpoint: "ws://C02FC1D4MD6T:8080/",
  walls: [
    { alive: true, position: { x: 0, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 1, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 2, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 3, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 4, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 5, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 6, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 7, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 8, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 9, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 1, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 2, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 3, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 4, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 5, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 6, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 7, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 8, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 9, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 1 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 2 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 3 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 4 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 5 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 6 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 7 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 8 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 9 }, type: "Strong" },
    { alive: true, position: { x: 0, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 0 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 1 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 2 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 3 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 4 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 5 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 6 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 7 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 8 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 9 }, type: "Strong" },
    { alive: true, position: { x: 10, y: 10 }, type: "Strong" },
    { alive: true, position: { x: 2, y: 2 }, type: "Strong" },
    { alive: true, position: { x: 2, y: 4 }, type: "Strong" },
    { alive: true, position: { x: 2, y: 6 }, type: "Strong" },
    { alive: true, position: { x: 2, y: 8 }, type: "Strong" },
    { alive: true, position: { x: 4, y: 2 }, type: "Strong" },
    { alive: true, position: { x: 4, y: 4 }, type: "Strong" },
    { alive: true, position: { x: 4, y: 6 }, type: "Strong" },
    { alive: true, position: { x: 4, y: 8 }, type: "Strong" },
    { alive: true, position: { x: 6, y: 2 }, type: "Strong" },
    { alive: true, position: { x: 6, y: 4 }, type: "Strong" },
    { alive: true, position: { x: 6, y: 6 }, type: "Strong" },
    { alive: true, position: { x: 6, y: 8 }, type: "Strong" },
    { alive: true, position: { x: 8, y: 2 }, type: "Strong" },
    { alive: true, position: { x: 8, y: 4 }, type: "Strong" },
    { alive: true, position: { x: 8, y: 6 }, type: "Strong" },
    { alive: true, position: { x: 8, y: 8 }, type: "Strong" },
    { alive: false, position: { x: 3, y: 1 }, type: "Weak" },
    { alive: true, position: { x: 7, y: 1 }, type: "Weak" },
    { alive: true, position: { x: 3, y: 5 }, type: "Weak" },
    { alive: true, position: { x: 7, y: 5 }, type: "Weak" },
    { alive: true, position: { x: 3, y: 9 }, type: "Weak" },
    { alive: true, position: { x: 7, y: 9 }, type: "Weak" },
    { alive: false, position: { x: 1, y: 3 }, type: "Weak" },
    { alive: true, position: { x: 5, y: 3 }, type: "Weak" },
    { alive: true, position: { x: 9, y: 3 }, type: "Weak" },
    { alive: true, position: { x: 1, y: 7 }, type: "Weak" },
    { alive: true, position: { x: 5, y: 7 }, type: "Weak" },
    { alive: true, position: { x: 9, y: 7 }, type: "Weak" },
  ],
};
